version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - lll
    - mnd
    - musttag
    - nakedret
    - nlreturn
    - nolintlint
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - revive
