name: Go
on:
  push:
    tags:
      - v*
    branches: [master, main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Vet
        run: find . -name go.mod -execdir go vet ./... \;

      - name: Test
        run: find . -name go.mod -execdir go test -f ./... \;
