name: Go
on:
  push:
    tags:
      - v*
    branches: [master, main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [http]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Vet
        run: go vet ./...
        working-directory: ${{ matrix.module }}

      - name: Test
        run: go test -v ./...
        working-directory: ${{ matrix.module }}
